config/routes.rb
Rails.application.routes.draw do

  resources :designations
  resources :information
  resources :website_details
  resources :products
  resources :statutories
  resources :biz_tabs
  resources :contact_details
  devise_for :users
  resources :users
  resources :form_detail_twos
  resources :form_detail_twos
  resources :form_detail_ones
  resources :form_detail_one
  resources :app_users do
    collection do
      post 'app_user_signup'
      get 'app_user_signin'
      get 'index_root'
      post 'submit_form_details'
      get 'create_users_roles'
      get 'generate_otp'
    end
  end
  root :to => 'app_users#index_root'

end

app/models/information.rb
class Information < ActiveRecord::Base
  belongs_to :user
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :authenticate_user!
  before_action :set_information, only: [:show, :edit, :update, :destroy]
  layout "dashboard"
  # GET /information
  # GET /information.json
  def index
    @information = Information.all
  end

  # GET /information/1
  # GET /information/1.json
  def show
  end

  # GET /information/new
  def new
    @information = Information.new
  end

  # GET /information/1/edit
  def edit
  end

  # POST /information
  # POST /information.json
  def create
    @information = Information.new(information_params)

    respond_to do |format|
      if @information.save
        format.html { redirect_to @information, notice: 'Information was successfully created.' }
        format.json { render :show, status: :created, location: @information }
      else
        format.html { render :new }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /information/1
  # PATCH/PUT /information/1.json
  def update
    respond_to do |format|
      if @information.update(information_params)
        format.html { redirect_to @information, notice: 'Information was successfully updated.' }
        format.json { render :show, status: :ok, location: @information }
      else
        format.html { render :edit }
        format.json { render json: @information.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /information/1
  # DELETE /information/1.json
  def destroy
    @information.destroy
    respond_to do |format|
      format.html { redirect_to information_index_url, notice: 'Information was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_information
      @information = Information.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def information_params
      params.require(:information).permit(:create_By, :sync_date, :sync_status, :google_status, :delivery_no, :delivery_status, :update_by_idil, :update_date_idil, :update_by_customer, :update_date_customer, :qc_date, :qc_by, :qc_status, :qc_remarks, :user_id)
    end
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/information/_form.html.erb
<%= form_for(@information) do |f| %>
  <% if @information.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@information.errors.count, "error") %> prohibited this information from being saved:</h2>

      <ul>
      <% @information.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :create_By %><br>
    <%= f.text_field :create_By %>
  </div>
  <div class="field">
    <%= f.label :sync_date %><br>
    <%= f.text_field :sync_date %>
  </div>
  <div class="field">
    <%= f.label :sync_status %><br>
    <%= f.text_field :sync_status %>
  </div>
  <div class="field">
    <%= f.label :google_status %><br>
    <%= f.text_field :google_status %>
  </div>
  <div class="field">
    <%= f.label :delivery_no %><br>
    <%= f.text_field :delivery_no %>
  </div>
  <div class="field">
    <%= f.label :delivery_status %><br>
    <%= f.text_field :delivery_status %>
  </div>
  <div class="field">
    <%= f.label :update_by_idil %><br>
    <%= f.text_field :update_by_idil %>
  </div>
  <div class="field">
    <%= f.label :update_date_idil %><br>
    <%= f.text_field :update_date_idil %>
  </div>
  <div class="field">
    <%= f.label :update_by_customer %><br>
    <%= f.text_field :update_by_customer %>
  </div>
  <div class="field">
    <%= f.label :update_date_customer %><br>
    <%= f.text_field :update_date_customer %>
  </div>
  <div class="field">
    <%= f.label :qc_date %><br>
    <%= f.text_field :qc_date %>
  </div>
  <div class="field">
    <%= f.label :qc_by %><br>
    <%= f.text_field :qc_by %>
  </div>
  <div class="field">
    <%= f.label :qc_status %><br>
    <%= f.text_field :qc_status %>
  </div>
  <div class="field">
    <%= f.label :qc_remarks %><br>
    <%= f.text_field :qc_remarks %>
  </div>
  <div class="field">
    <% f.label :user_id %><br>
    <% f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/information/edit.html.erb
<h1>Editing Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @information %> |
<%= link_to 'Back', information_index_path %>

app/views/information/index.html.erb
<p id="notice"><%= notice %></p>
<h3 align="center">Listing Information</h3>
<table class="table table-striped table-bordered" id="information">
  <thead>
    <tr>
      <th>Create by</th>
      <th>Sync date</th>
      <th>Sync status</th>
      <th>Google status</th>
      <th>Delivery no</th>
      <th>Delivery status</th>
      <th>Update by idil</th>
      <th>Update date idil</th>
      <th>Update by customer</th>
      <th>Update date customer</th>
      <th>Qc date</th>
      <th>Qc by</th>
      <th>Qc status</th>
      <th>Qc remarks</th>
      <!-- <th>User</th> -->
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @information.each do |information| %>
      <tr>
        <td><%= information.create_By %></td>
        <td><%= information.sync_date %></td>
        <td><%= information.sync_status %></td>
        <td><%= information.google_status %></td>
        <td><%= information.delivery_no %></td>
        <td><%= information.delivery_status %></td>
        <td><%= information.update_by_idil %></td>
        <td><%= information.update_date_idil %></td>
        <td><%= information.update_by_customer %></td>
        <td><%= information.update_date_customer %></td>
        <td><%= information.qc_date %></td>
        <td><%= information.qc_by %></td>
        <td><%= information.qc_status %></td>
        <td><%= information.qc_remarks %></td>
        <!-- <td><%= information.user %></td> -->
        <td><%= link_to 'Show', information %>
        <%= link_to 'Edit', edit_information_path(information) %>
        <%= link_to 'Destroy', information, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% link_to 'New Information', new_information_path %>

app/views/information/new.html.erb
<h1>New Information</h1>

<%= render 'form' %>

<%= link_to 'Back', information_index_path %>

app/views/information/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Create by:</strong>
  <%= @information.create_By %>
</p>

<p>
  <strong>Sync date:</strong>
  <%= @information.sync_date %>
</p>

<p>
  <strong>Sync status:</strong>
  <%= @information.sync_status %>
</p>

<p>
  <strong>Google status:</strong>
  <%= @information.google_status %>
</p>

<p>
  <strong>Delivery no:</strong>
  <%= @information.delivery_no %>
</p>

<p>
  <strong>Delivery status:</strong>
  <%= @information.delivery_status %>
</p>

<p>
  <strong>Update by idil:</strong>
  <%= @information.update_by_idil %>
</p>

<p>
  <strong>Update date idil:</strong>
  <%= @information.update_date_idil %>
</p>

<p>
  <strong>Update by customer:</strong>
  <%= @information.update_by_customer %>
</p>

<p>
  <strong>Update date customer:</strong>
  <%= @information.update_date_customer %>
</p>

<p>
  <strong>Qc date:</strong>
  <%= @information.qc_date %>
</p>

<p>
  <strong>Qc by:</strong>
  <%= @information.qc_by %>
</p>

<p>
  <strong>Qc status:</strong>
  <%= @information.qc_status %>
</p>

<p>
  <strong>Qc remarks:</strong>
  <%= @information.qc_remarks %>
</p>

<p>
  <strong>User:</strong>
  <%= @information.user %>
</p>

<%= link_to 'Edit', edit_information_path(@information) %> |
<%= link_to 'Back', information_index_path %>