config/routes.rb
Rails.application.routes.draw do

  resources :designations
  resources :information
  resources :website_details
  resources :products
  resources :statutories
  resources :biz_tabs
  resources :contact_details
  devise_for :users
  resources :users
  resources :form_detail_twos
  resources :form_detail_twos
  resources :form_detail_ones
  resources :form_detail_one
  resources :app_users do
    collection do
      post 'app_user_signup'
      get 'app_user_signin'
      get 'index_root'
      post 'submit_form_details'
      get 'create_users_roles'
      get 'generate_otp'
    end
  end
  root :to => 'app_users#index_root'

end

app/models/designation.rb
class Designation < ActiveRecord::Base
	validates :name, presence: true, length: {in: 2..100}
end

app/controllers/designations_controller.rb
class DesignationsController < ApplicationController
  before_action :set_designation, only: [:show, :edit, :update, :destroy]
  layout "dashboard"

  # GET /designations
  # GET /designations.json
  def index
    @designations = Designation.all
  end

  # GET /designations/1
  # GET /designations/1.json
  def show
  end

  # GET /designations/new
  def new
    @designation = Designation.new
  end

  # GET /designations/1/edit
  def edit
  end

  # POST /designations
  # POST /designations.json
  def create
    @designation = Designation.new(designation_params)

    respond_to do |format|
      if @designation.save
        format.html { redirect_to @designation, notice: 'Designation was successfully created.' }
        format.json { render :show, status: :created, location: @designation }
      else
        format.html { render :new }
        format.json { render json: @designation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designations/1
  # PATCH/PUT /designations/1.json
  def update
    respond_to do |format|
      if @designation.update(designation_params)
        format.html { redirect_to @designation, notice: 'Designation was successfully updated.' }
        format.json { render :show, status: :ok, location: @designation }
      else
        format.html { render :edit }
        format.json { render json: @designation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designations/1
  # DELETE /designations/1.json
  def destroy
    @designation.destroy
    respond_to do |format|
      format.html { redirect_to designations_url, notice: 'Designation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_designation
      @designation = Designation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def designation_params
      params.require(:designation).permit(:name)
    end
end

app/helpers/designations_helper.rb
module DesignationsHelper
end

app/views/designations/_form.html.erb
<%= form_for(@designation) do |f| %>
  <% if @designation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@designation.errors.count, "error") %> prohibited this designation from being saved:</h2>

      <ul>
      <% @designation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designations/edit.html.erb
<h1>Editing Designation</h1>

<%= render 'form' %>

<%= link_to 'Show', @designation %> |
<%= link_to 'Back', designations_path %>

app/views/designations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Designations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designations.each do |designation| %>
      <tr>
        <td><%= designation.name %></td>
        <td><%= link_to 'Show', designation %></td>
        <td><%= link_to 'Edit', edit_designation_path(designation) %></td>
        <td><%= link_to 'Destroy', designation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Designation', new_designation_path %>

<div class="container">
<% @designations.each do |designation| %>
  <div class="wrapper">
    <h4><%= designation.name %></h4>
    <div style=""><%= link_to 'Show', designation %>|<%= link_to 'Edit', edit_designation_path(designation) %>|<%= link_to 'Destroy', designation, method: :delete, data: { confirm: 'Are you sure?' } %></div>
  </div>
<% end %>
  <%= link_to 'New Designation', new_designation_path %>
</div>

app/views/designations/new.html.erb
<h1>New Designation</h1>

<%= render 'form' %>

<%= link_to 'Back', designations_path %>

app/views/designations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @designation.name %>
</p>

<%= link_to 'Edit', edit_designation_path(@designation) %> |
<%= link_to 'Back', designations_path %>