config/routes.rb
Rails.application.routes.draw do

  resources :designations
  resources :information
  resources :website_details
  resources :products
  resources :statutories
  resources :biz_tabs
  resources :contact_details
  devise_for :users
  resources :users
  resources :form_detail_twos
  resources :form_detail_twos
  resources :form_detail_ones
  resources :form_detail_one
  resources :app_users do
    collection do
      post 'app_user_signup'
      get 'app_user_signin'
      get 'index_root'
      post 'submit_form_details'
      get 'create_users_roles'
      get 'generate_otp'
    end
  end
  root :to => 'app_users#index_root'

end

app/models/app_user.rb
class AppUser < ActiveRecord::Base
	belongs_to :user

	validates :email, 
	uniqueness: true, 
	presence: true,
	format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "please enter a valid email" }
	
	validates :name, presence: true, length: {in: 4..90}

	validates :mobile_no, 
	uniqueness: true, 
	format: {with: /\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/, message: "please enter a valid mobile number"}, 
	length: { is: 10 }

end

app/controllers/app_users_controller.rb
class AppUsersController < ApplicationController
  before_action :authenticate_user!, :except => [:app_user_signin,:submit_form_details]
  skip_before_filter :verify_authenticity_token
  before_action :set_app_user, only: [:show, :edit, :update, :destroy]
  layout "dashboard"
  # GET /app_users
  # GET /app_users.json
  def index
    @app_users = AppUser.all
  end
  
  def index_root
    
  end
  
  def create_users_roles
  @current_user = current_user
    
  end
  
  def generate_otp
    
  end
  # GET /app_users/1
  # GET /app_users/1.json
  def show
  end

  # GET /app_users/new
  def new
    @app_user = AppUser.new
  end

  # GET /app_users/1/edit
  def edit
  end

  # POST /app_users
  # POST /app_users.json
  def create
    @app_user = AppUser.new(app_user_params)
    all = AppUser.all.map{|m|m.user_name}
    if all.include?params["app_user"]["user_name"]
     redirect_to :back,:alert => "User Already Exists Can't Create Duplicate User" 
    else
    respond_to do |format|
      if @app_user.save
        format.html { redirect_to @app_user, notice: 'App user was successfully created.' }
        format.json { render :show, status: :created, location: @app_user }
      else
        format.html { render :new }
        format.json { render json: @app_user.errors, status: :unprocessable_entity }
      end  
      end
    end
  end

  # PATCH/PUT /app_users/1
  # PATCH/PUT /app_users/1.json
  def update
    respond_to do |format|
      if @app_user.update(app_user_params)
        format.html { redirect_to @app_user, notice: 'App user was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_user }
      else
        format.html { render :edit }
        format.json { render json: @app_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_users/1
  # DELETE /app_users/1.json
  def destroy
    @app_user.destroy
    respond_to do |format|
      format.html { redirect_to app_users_url, notice: 'App user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def app_user_signup
    render :json => {:success=>false,:message => "Please provide User Name"} and return if  params[:app_user]["user_name"].blank?
    render :json => {:success=>false,:message => "Please provide Email"} and return if  params[:app_user]["email"].blank?
    render :json => {:success=>false,:message => "Please provide Mobile No"} and return if  params[:app_user]["mobile_no"].blank?
    user_name_arr = AppUser.all.map{|name|name.user_name}
    email_arr = AppUser.all.map{|e|e.email}
    mobile_no_arr = AppUser.all.map{|m|m.mobile_no} 
    if(mobile_no_arr.include?params[:app_user]["mobile_no"])
    render :json => {:success => false,:message => "Mobile No Exists"}
    else  
    AppUser.create(:user_name=>params[:app_user]["user_name"],:email=>params[:app_user]["email"],:mobile_no=>params[:app_user]["mobile_no"])
    render :json => {:success=>true,:message=>"Data saved successfully"} 
    end
  end
  
  def app_user_signin
   user_name_arr = AppUser.all.map{|u|u.user_name}
   password_arr = AppUser.all.map{|p|p.password}
   if((user_name_arr.include?params["user_name"]) && (password_arr.include?params["password"]))
     render :json => {:success=>true,:message=>"Welcome to App"}
   else
     render :json => {:success=>false,:message=>"Invalid Mobile No/User Name"}
  end
  end
  
  def submit_form_details
  render :json => {:success=>false,:message => "Please provide contact person"} and return if params[:contact_person].blank? 
  render :json => {:success=>false,:message => "Please provide designation"} and return if params[:designation].blank?  
  render :json => {:success=>false,:message => "Please provide company_name"} and return if params[:company_name].blank? 
  render :json => {:success=>false,:message => "Please provide city"} and return if params[:city].blank?
  render :json => {:success=>false,:message => "Please provide state"} and return if params[:state].blank? 
  render :json => {:success=>false,:message => "Please provide locality"} and return if params[:locality].blank?  
  render :json => {:success=>false,:message => "Please provide postal code"} and return if params[:postal_code].blank?
  render :json => {:success=>false,:message => "Please provide address1"} and return if params[:address1].blank?
  render :json => {:success=>false,:message => "Please provide address2"} and return if params[:address2].blank?
  render :json => {:success=>false,:message => "Please provide area/landmark"} and return if params[:area].blank?
  render :json => {:success=>false,:message => "Please provide primary mpbile1"} and return if params[:mobile1].blank?
  render :json => {:success=>false,:message => "Please provide terms and conditions"} and return if params[:terms_condition].blank?
   render :json => {:success=>false,:message => "Please provide terms and signature"} and return if params[:signature].blank?
  obj1 = ContactDetail.new
  obj1.contact_person = params[:contact_person]
  obj1.designation = params[:designation]
  obj1.ceo_name = params[:ceo_name]
  obj1.company_name = params[:company_name]
  obj1.country = params[:country]
  obj1.city = params[:city]
  obj1.state = params[:state]
  obj1.locality = params[:locality]
  obj1.postal_code = params[:postal_code]
  obj1.address1 = params[:address1]
  obj1.address2 = params[:address2]
  obj1.area = params[:area]
  obj1.contact_person_no = params[:contact_person_no]
  obj1.mobile1 = params[:mobile1]
  obj1.mobile2 = params[:mobile2]
  obj1.primary_email = params[:primary_email]
  obj1.alternate_email = params[:alternate_email]
  obj1.legal_owner = params[:legal_owner]
  obj1.visiting_card_front_image = params[:visiting_card_front_image]
  obj1.visiting_card_back_image = params[:visiting_card_back_image]
  obj1.business_category = params[:business_category]
  obj1.terms_condition = params[:terms_condition]
  obj1.signature = params[:signature]
  obj1.save
  render :json => {:success=>false,:message => "Please provide primary business type"} and return if params[:primary_business_type].blank?
  render :json => {:success=>false,:message => "Please provide year of establishment"} and return if params[:year_of_establishment].blank?
  render :json => {:success=>false,:message => "Please provide no of employees"} and return if params[:no_of_employees].blank?
  render :json => {:success=>false,:message => "Please provide annual sales"} and return if params[:annual_sales].blank?
  render :json => {:success=>false,:message => "Please provide ownership type"} and return if params[:ownership_type].blank?
  render :json => {:success=>false,:message => "Please provide additional businesses"} and return if params[:additional_businesses].blank?
  render :json => {:success=>false,:message => "Please provide business day"} and return if params[:business_day].blank?
  render :json => {:success=>false,:message => "Please provide business hours"} and return if params[:business_hours].blank?
  obj2 = BizTab.new
  obj2.primary_business_type = params[:primary_business_type]
  obj2.company_logo = params[:company_logo]
  obj2.website = params[:website]
  obj2.about_us = params[:about_us]
  obj2.year_of_establishment = params[:year_of_establishment]
  obj2.no_of_employees = params[:no_of_employees]
  obj2.annual_sales = params[:annual_sales]
  obj2.ownership_type = params[:ownership_type]
  obj2.alternate_website = params[:alternate_website]
  obj2.additional_businesses = params[:additional_businesses]
  obj2.office_type = params[:office_type]
  obj2.question = params[:question]
  obj2.office_interior_image = params[:office_interior_image]
  obj2.office_exterior_image = params[:office_exterior_image]
  obj2.bankers_details = params[:bankers_details]
  obj2.business_day = params[:business_day]
  obj2.business_hours = params[:business_hours]
  obj2.specialization = params[:specialization]
  obj2.remarks = params[:remarks]
  obj2.deals_in = params[:deals_in]
  obj2.business_preferred_area = params[:business_preferred_area]
  obj2.save
  unless params[:reg_no].nil? && params[:reg_authority].nil? &&  params[:cin_no].nil? && params[:tan_no].nil? && params[:pan_no].nil? && params[:service_tax_no].nil? && params[:excise_reg_no].nil? && params[:nsic_no].nil?
  obj3 = Statutory.new
  obj3.reg_no = params[:reg_no]
  obj3.reg_authority = params[:reg_authority]
  obj3.cin_no = params[:cin_no]
  obj3.tan_no = params[:tan_no]
  obj3.pan_no = params[:pan_no]
  obj3.service_tax_no = params[:service_tax_no]
  obj3.excise_reg_no = params[:excise_reg_no]
  obj3.tin_no = params[:tin_no]
  obj3.dgft = params[:dgft]
  obj3.cst_no = params[:cst_no]
  obj3.ssi_no = params[:ssi_no]
  obj3.epf_no = params[:epf_no]
  obj3.esi_no = params[:esi_no]
  obj3.sct_no = params[:sct_no]
  obj3.dnb_no = params[:dnb_no]
  obj3.rbi_no = params[:rbi_no]
  obj3.fssai = params[:fssai]
  obj3.nsic_no = params[:nsic_no]
  obj3.sst_no = params[:sst_no]
  obj3.save
  end
  render :json => {:success=>false,:message => "Please provide top 5 products"} and return if params[:top_5].blank?
  unless params[:add_product].nil? && params[:min_order_quantity].nil? && params[:top_5].nil? 
  obj4 = Product.new
  obj4.add_product = params[:add_product]
  obj4.product_name = params[:product_name]
  obj4.approx_price = params[:approx_price]
  obj4.min_order_quantity = params[:min_order_quantity]
  obj4.unit_type = params[:unit_type]
  obj4.product_group = params[:product_group]
  obj4.product_desc = params[:product_desc]
  obj4.product_image = params[:product_image]
  obj4.top_5 = params[:top_5]
  obj4.save
  end
  unless params[:hp_key_desc].nil? && params[:au_profile_heading].nil? &&  params[:infra_acilities_image].nil? && params[:testimonial_image].nil? &&  params[:trademarks].nil?
  obj5 = WebsiteDetail.new
  obj5.hp_key_desc = params[:hp_key_desc]
  obj5.hp_image = params[:hp_image]
  obj5.hp_detail_desc = params[:hp_detail_desc]

app/helpers/app_users_helper.rb
module AppUsersHelper
end

app/views/app_users/_form.html.erb
<%= form_for(@app_user) do |f| %>
  <% if @app_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app_user.errors.count, "error") %> prohibited this app_user from being saved:</h2>

      <ul>
      <% @app_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :mobile_no %><br>
    <%= f.text_field :mobile_no %>
  </div> 
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div> 

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit :create, :class=>"btn btn-success"%>
  </div>
<% end %>

app/views/app_users/create_users_roles.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title></title>
</head>
<body>
<div class="container">
    <h2>Create User and Roles</h2>
    <%= form_tag create_users_roles_app_users_path, method: :get, :id=>"role" do %>	
    <div class="form-group">
    <label for="email">Email:</label>
    <%= text_field_tag 'email',nil,class: "form-control",:placeholder=>"email"%></div>
    <div class="form-group">
    <label for="pwd">Password:</label>
    <%= text_field_tag 'password',nil,class: "form-control",:placeholder=>"password"%></div>
    <div class="form-group">
    <label for="pwd">Role:</label>
    <%=select_tag "role", options_for_select(["sub_admin","client"],"Select")%>
    </div>
    <div class="form-group">
    <label for="pwd">Contact Person:</label>
    <%= check_box "contact_persons", "enabled", {}, "1", "0" %>
    </div>
    <div class="form-group">
    <label for="pwd">Biz Tabs:</label>
    <%= check_box "biz_tabs", "enabled", {}, "1", "0" %>
    </div>
    <div class="form-group">
    <label for="pwd">Statutory:</label>
    <%= check_box "statutory", "enabled", {}, "1", "0" %>
    </div>
     <div class="form-group">
    <label for="pwd">Product:</label>
    <%= check_box "product", "enabled", {}, "1", "0" %>
    </div>
    <div class="form-group">
    <label for="pwd">Website Details:</label>
    <%= check_box "website_details", "enabled", {}, "1", "0" %>
    </div>
    <div class="form-group">
    <label for="pwd">Information:</label>
    <%= check_box "information", "enabled", {}, "1", "0" %>
    </div><br>
    <%= submit_tag 'AssignRole',class:"btn btn-success", :id=>"btnrole"%>
    <%end%> 
</div>        
</body>
</html>

app/views/app_users/edit.html.erb
<h3>Editing App User</h3>

<%= render 'form' %>

<%= link_to 'Show', @app_user %> |
<%= link_to 'Back', app_users_path %>

app/views/app_users/generate_otp.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<title></title>
</head>
<body>
<div class="container">
    <h2>Send OTP</h2>
    <%= form_tag root_path, method: :get, :id=>"role" do %>	
    <div class="form-group">
    <label for="email">Phone No:</label>
    <%= text_field_tag 'OTP',nil,class: "form-control"%>
    </div><br><br>
    <div class="form-group">
    <%= submit_tag 'submit',class:"btn btn-success", :id=>"btnotp"%>
    </div>
    <%end%> 
</div>        
</body>
</html>

app/views/app_users/index.html.erb
<p id="notice"><%= notice %></p>

<h3 align="center">App Users</h3>
<table class="table table-striped table-bordered" id="appuser">
  <thead>
    <tr>
      <th>User name</th>
      <th>Email</th>
      <th>Mobile no</th>
      <th>City</th>
      <th>Created By</th>
      <th>Password</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @app_users.each do |app_user| %>
      <tr>
        <td><%= app_user.user_name %></td>
        <td><%= app_user.email %></td>
        <td><%= app_user.mobile_no %></td>
        <td><%= app_user.city %></td>
        <td><%= User.find(app_user.user_id).email %></td>
        <td><%= app_user.password %></td>
        <td><%= link_to '<i class="fa fa-eye" data-container="body" title="View Record" rel="popover"></i>'.html_safe, app_user, :class=>"btn btn-primary" %>
        <%= link_to '<i class="fa fa-pencil-square" data-container="body" title="Edit Record" rel="popover"></i>'.html_safe, edit_app_user_path(app_user),:class=>"btn btn-primary" %>
        <%= link_to '<i class="fa fa-trash" data-container="body" title="Delete Record" rel="popover"></i>'.html_safe, app_user, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create App user', new_app_user_path,:class=>"btn btn-primary"%>

app/views/app_users/index_root.html.erb
	<section class="content">
	<div class="row" style="margin-bottom:5px;">
	<div class="col-md-3">
    <div class="sm-st clearfix">
    <span class="sm-st-icon st-red"><i class="fa fa-file-text"></i></i></span>
    <div class="sm-st-info">
    <span>0</span>
    View
    </div>
    </div>
    </div>
    <div class="col-md-3">
    <div class="sm-st clearfix">
    <span class="sm-st-icon st-violet"><i class="fa fa-file-text"></i></span>
    <div class="sm-st-info">
    <span>0</span>
    View
    </div>
    </div>
    </div>
    <div class="col-md-3">
    <div class="sm-st clearfix">
    <span class="sm-st-icon st-blue"><i class="fa fa-file-text"></i></span>
    <div class="sm-st-info">
    <span>0</span>
    View
    </div>
    </div>
    </div>
    <div class="col-md-3">
    <div class="sm-st clearfix">
    <span class="sm-st-icon st-green"><i class="fa fa-users"></i></span>
    <div class="sm-st-info">
    <span>0</span>
    View
    </div>
    </div>
    </div>
    </div>
    <p align="center">Welcome Page</p>
    </section><!-- /.content -->

app/views/app_users/new.html.erb
<h1>App User</h1>

<%= render 'form' %>

<%= link_to 'Back', app_users_path %>

app/views/app_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @app_user.user_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @app_user.email %>
</p>
<p>
  <strong>Mobile no:</strong>
  <%= @app_user.mobile_no %>
</p>
<p>
  <strong>Email:</strong>
  <%= @app_user.city %>
</p>
<p>
  <strong>Email:</strong>
  <%= User.find(@app_user.user_id).email %>
</p>
<p>
  <strong>password:</strong>
  <%= @app_user.password %>
</p>
<%= link_to 'Edit', edit_app_user_path(@app_user) %> |
<%= link_to 'Back', app_users_path %>