config/routes.rb
Rails.application.routes.draw do

  resources :designations
  resources :information
  resources :website_details
  resources :products
  resources :statutories
  resources :biz_tabs
  resources :contact_details
  devise_for :users
  resources :users
  resources :form_detail_twos
  resources :form_detail_twos
  resources :form_detail_ones
  resources :form_detail_one
  resources :app_users do
    collection do
      post 'app_user_signup'
      get 'app_user_signin'
      get 'index_root'
      post 'submit_form_details'
      get 'create_users_roles'
      get 'generate_otp'
    end
  end
  root :to => 'app_users#index_root'

end

app/models/website_detail.rb
class WebsiteDetail < ActiveRecord::Base
  belongs_to :user
  has_attached_file :hp_image,
    :path => ":rails_root/public/system/hp_image/:id/:style/:basename.:extension", 
    :url => "/system/hp_image/:id/:style/:basename.:extension"
  do_not_validate_attachment_file_type :hp_image
  
  has_attached_file :award_image,
    :path => ":rails_root/public/system/award_image/:id/:style/:basename.:extension", 
    :url => "/system/award_image/:id/:style/:basename.:extension"
  do_not_validate_attachment_file_type :award_image
  
   has_attached_file :qc_image,
    :path => ":rails_root/public/system/qc_image/:id/:style/:basename.:extension", 
    :url => "/system/qc_image/:id/:style/:basename.:extension"
   do_not_validate_attachment_file_type :qc_image
   
   has_attached_file :infra_acilities_image,
    :path => ":rails_root/public/system/infra_acilities_image/:id/:style/:basename.:extension", 
    :url => "/system/infra_acilities_image/:id/:style/:basename.:extension"
   do_not_validate_attachment_file_type :infra_acilities_image
   
   has_attached_file :testimonial_image,
    :path => ":rails_root/public/system/testimonial_image/:id/:style/:basename.:extension", 
    :url => "/system/testimonial_image/:id/:style/:basename.:extension"
   do_not_validate_attachment_file_type :testimonial_image
   
   has_attached_file :news_image,
    :path => ":rails_root/public/system/news_image/:id/:style/:basename.:extension", 
    :url => "/system/news_image/:id/:style/:basename.:extension"
   do_not_validate_attachment_file_type :news_image
   
   has_attached_file :custom_profile_image,
    :path => ":rails_root/public/system/custom_profile_image/:id/:style/:basename.:extension", 
    :url => "/system/custom_profile_image/:id/:style/:basename.:extension"
   do_not_validate_attachment_file_type :custom_profile_image

   def self.search(dateF, agentF)
    if dateF || agentF
      where(["created_at LIKE ?", "%#{dateF}%"]).all
      where(["created_by LIKE ?", "%#{agentF}%"]).all
    else
      all.order("created_at ASC")
    end
  end

end

app/controllers/website_details_controller.rb
class WebsiteDetailsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_website_detail, only: [:show, :edit, :update, :destroy]
  layout "dashboard"
  # GET /website_details
  # GET /website_details.json
  def index
    #@website_details = WebsiteDetail.all

    @website_details = WebsiteDetail.search(params[:dateF], params[:agentF])
    
  end

  # GET /website_details/1
  # GET /website_details/1.json
  def show
  end

  # GET /website_details/new
  def new
    @website_detail = WebsiteDetail.new
  end

  # GET /website_details/1/edit
  def edit
  end

  # POST /website_details
  # POST /website_details.json
  def create
    @website_detail = WebsiteDetail.new(website_detail_params)

    respond_to do |format|
      if @website_detail.save
        format.html { redirect_to @website_detail, notice: 'Website detail was successfully created.' }
        format.json { render :show, status: :created, location: @website_detail }
      else
        format.html { render :new }
        format.json { render json: @website_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /website_details/1
  # PATCH/PUT /website_details/1.json
  def update
    respond_to do |format|
      if @website_detail.update(website_detail_params)
        format.html { redirect_to @website_detail, notice: 'Website detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @website_detail }
      else
        format.html { render :edit }
        format.json { render json: @website_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /website_details/1
  # DELETE /website_details/1.json
  def destroy
    @website_detail.destroy
    respond_to do |format|
      format.html { redirect_to website_details_url, notice: 'Website detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website_detail
      @website_detail = WebsiteDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_detail_params
      params.require(:website_detail).permit(:hp_key_desc, :hp_detail_desc, :au_profile_heading, :au_profile_desc, :awards_heading, :awards_desc, :qc_heading, :qc_desc, :infra_heading, :infra_desc, :testimonial_date, :testimonial_desc, :news_date, :news_headline, :news_coverage_url, :news_desc, :job_title, :job_desc, :cp_heading, :cp_desc, :products, :team, :cert_heading, :cert_details, :valid_from, :valid_till, :issued_on, :issued_by, :honour_award, :patents, :trademarks, :created_by, :updated_by, :deleted_by, :user_id, :hp_image, :award_image, :qc_image, :infra_acilities_image, :testimonial_image, :news_image, :custom_profile_image)
    end
end

app/helpers/website_details_helper.rb
module WebsiteDetailsHelper
end

app/views/website_details/_form.html.erb
<%= form_for(@website_detail) do |f| %>
  <% if @website_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@website_detail.errors.count, "error") %> prohibited this website_detail from being saved:</h2>

      <ul>
      <% @website_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hp_key_desc %><br>
    <%= f.text_field :hp_key_desc %>
  </div>
  <div class="field">
    <%= f.label :hp_detail_desc %><br>
    <%= f.text_field :hp_detail_desc %>
  </div>
  <div class="field">
    <%= f.label :au_profile_heading %><br>
    <%= f.text_field :au_profile_heading %>
  </div>
  <div class="field">
    <%= f.label :au_profile_desc %><br>
    <%= f.text_field :au_profile_desc %>
  </div>
  <div class="field">
    <%= f.label :awards_heading %><br>
    <%= f.text_field :awards_heading %>
  </div>
  <div class="field">
    <%= f.label :awards_desc %><br>
    <%= f.text_field :awards_desc %>
  </div>
  <div class="field">
    <%= f.label :qc_heading %><br>
    <%= f.text_field :qc_heading %>
  </div>
  <div class="field">
    <%= f.label :qc_desc %><br>
    <%= f.text_field :qc_desc %>
  </div>
  <div class="field">
    <%= f.label :infra_heading %><br>
    <%= f.text_field :infra_heading %>
  </div>
  <div class="field">
    <%= f.label :infra_desc %><br>
    <%= f.text_field :infra_desc %>
  </div>
  <div class="field">
    <%= f.label :testimonial_date %><br>
    <%= f.text_field :testimonial_date %>
  </div>
  <div class="field">
    <%= f.label :testimonial_desc %><br>
    <%= f.text_field :testimonial_desc %>
  </div>
  <div class="field">
    <%= f.label :news_date %><br>
    <%= f.text_field :news_date %>
  </div>
  <div class="field">
    <%= f.label :news_headline %><br>
    <%= f.text_area :news_headline %>
  </div>
  <div class="field">
    <%= f.label :news_coverage_url %><br>
    <%= f.text_area :news_coverage_url %>
  </div>
  <div class="field">
    <%= f.label :news_desc %><br>
    <%= f.text_area :news_desc %>
  </div>
  <div class="field">
    <%= f.label :job_title %><br>
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :job_desc %><br>
    <%= f.text_area :job_desc %>
  </div>
  <div class="field">
    <%= f.label :cp_heading %><br>
    <%= f.text_field :cp_heading %>
  </div>
  <div class="field">
    <%= f.label :cp_desc %><br>
    <%= f.text_field :cp_desc %>
  </div>
  <div class="field">
    <%= f.label :products %><br>
    <%= f.text_field :products %>
  </div>
  <div class="field">
    <%= f.label :team %><br>
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :cert_heading %><br>
    <%= f.text_field :cert_heading %>
  </div>
  <div class="field">
    <%= f.label :cert_details %><br>
    <%= f.text_field :cert_details %>
  </div>
  <div class="field">
    <%= f.label :valid_from %><br>
    <%= f.text_field :valid_from %>
  </div>
  <div class="field">
    <%= f.label :valid_till %><br>
    <%= f.text_field :valid_till %>
  </div>
  <div class="field">
    <%= f.label :issued_on %><br>
    <%= f.text_field :issued_on %>
  </div>
  <div class="field">
    <%= f.label :issued_by %><br>
    <%= f.text_field :issued_by %>
  </div>
  <div class="field">
    <%= f.label :honour_award %><br>
    <%= f.text_field :honour_award %>
  </div>
  <div class="field">
    <%= f.label :patents %><br>
    <%= f.text_field :patents %>
  </div>
  <div class="field">
    <%= f.label :trademarks %><br>
    <%= f.text_field :trademarks %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <% f.label :updated_by %><br>
    <% f.text_field :updated_by %>
  </div>
  <div class="field">
    <% f.label :deleted_by %><br>
    <% f.text_field :deleted_by %>
  </div>
  <div class="field">
    <% f.label :user_id %><br>
    <% f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/website_details/edit.html.erb
<h1>Editing Website Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @website_detail %> |
<%= link_to 'Back', website_details_path %>

app/views/website_details/index.html.erb
  <br>
  <%=form_tag website_details_path, method: 'get' do%>
            
    <input type="date" name="dateF" id="dateF" value="<%=params[:dateF].to_s%>" >

    <select type="text" name="agentF" id="agentF" value="<%=params[:agentF].to_s%>" style="box-shadow:none;border:1px solid #67696f;height:40px;background-color:#fff;">
        <option value="">Select</option>>
      <%AppUser.all.each do |k|%>
        <option value="<%=k.id%>"><%=k.email%></option>
      <%end%>
    </select>

    <%=submit_tag ('Search'),name: nil,class: "btn btn-danger", style: "height:40px;"%>
  <%end%>
    <br>

<p id="notice"><%= notice %></p>

<h3 align="center">Listing Website Details</h3>
<table class="table table-striped table-bordered" id="website_details">
  <thead>
    <tr>
      <th>Hp key desc</th>
      <th>Hp detail desc</th>
      <th>Au profile heading</th>
      <th>Au profile desc</th>
      <th>Awards heading</th>
      <th>Awards desc</th>
      <th>Qc heading</th>
      <th>Qc desc</th>
      <th>Infra heading</th>
      <th>Infra desc</th>
      <th>Testimonial date</th>
      <th>Testimonial desc</th>
      <th>News date</th>
      <th>News headline</th>
      <th>News coverage url</th>
      <th>News desc</th>
      <th>Job title</th>
      <th>Job desc</th>
      <th>Cp heading</th>
      <th>Cp desc</th>
      <th>Products</th>
      <th>Team</th>
      <th>Cert heading</th>
      <th>Cert details</th>
      <th>Valid from</th>
      <th>Valid till</th>
      <th>Issued on</th>
      <th>Issued by</th>
      <th>Honour award</th>
      <th>Patents</th>
      <th>Trademarks</th>
      <th>Created by</th>
      <!-- <th>Updated by</th>
      <th>Deleted by</th>
      <th>User</th> -->
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @website_details.each do |website_detail| %>
      <tr>
        <td><%= website_detail.hp_key_desc %></td>
        <td><%= website_detail.hp_detail_desc %></td>
        <td><%= website_detail.au_profile_heading %></td>
        <td><%= website_detail.au_profile_desc %></td>
        <td><%= website_detail.awards_heading %></td>
        <td><%= website_detail.awards_desc %></td>
        <td><%= website_detail.qc_heading %></td>
        <td><%= website_detail.qc_desc %></td>
        <td><%= website_detail.infra_heading %></td>
        <td><%= website_detail.infra_desc %></td>
        <td><%= website_detail.testimonial_date %></td>
        <td><%= website_detail.testimonial_desc %></td>
        <td><%= website_detail.news_date %></td>
        <td><%= website_detail.news_headline %></td>
        <td><%= website_detail.news_coverage_url %></td>
        <td><%= website_detail.news_desc %></td>
        <td><%= website_detail.job_title %></td>
        <td><%= website_detail.job_desc %></td>
        <td><%= website_detail.cp_heading %></td>
        <td><%= website_detail.cp_desc %></td>
        <td><%= website_detail.products %></td>
        <td><%= website_detail.team %></td>
        <td><%= website_detail.cert_heading %></td>
        <td><%= website_detail.cert_details %></td>
        <td><%= website_detail.valid_from %></td>
        <td><%= website_detail.valid_till %></td>
        <td><%= website_detail.issued_on %></td>
        <td><%= website_detail.issued_by %></td>
        <td><%= website_detail.honour_award %></td>
        <td><%= website_detail.patents %></td>
        <td><%= website_detail.trademarks %></td>
        <td><%= website_detail.created_by %></td>
        <!-- <td><%= website_detail.updated_by %></td>
        <td><%= website_detail.deleted_by %></td>
        <td><%= website_detail.user %></td> -->
        <td><%= link_to 'Show', website_detail %>
        <%= link_to 'Edit', edit_website_detail_path(website_detail) %>
        <%= link_to 'Destroy', website_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% link_to 'New Website detail', new_website_detail_path %>

app/views/website_details/new.html.erb
<h1>New Website Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', website_details_path %>

app/views/website_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hp key desc:</strong>
  <%= @website_detail.hp_key_desc %>
</p>

<p>
  <strong>Hp detail desc:</strong>
  <%= @website_detail.hp_detail_desc %>
</p>

<p>
  <strong>Au profile heading:</strong>
  <%= @website_detail.au_profile_heading %>
</p>

<p>
  <strong>Au profile desc:</strong>
  <%= @website_detail.au_profile_desc %>
</p>

<p>
  <strong>Awards heading:</strong>
  <%= @website_detail.awards_heading %>
</p>

<p>
  <strong>Awards desc:</strong>
  <%= @website_detail.awards_desc %>
</p>

<p>
  <strong>Qc heading:</strong>
  <%= @website_detail.qc_heading %>
</p>

<p>
  <strong>Qc desc:</strong>
  <%= @website_detail.qc_desc %>
</p>

<p>
  <strong>Infra heading:</strong>
  <%= @website_detail.infra_heading %>
</p>

<p>
  <strong>Infra desc:</strong>
  <%= @website_detail.infra_desc %>
</p>

<p>
  <strong>Testimonial date:</strong>
  <%= @website_detail.testimonial_date %>
</p>

<p>
  <strong>Testimonial desc:</strong>
  <%= @website_detail.testimonial_desc %>
</p>

<p>
  <strong>News date:</strong>
  <%= @website_detail.news_date %>
</p>

<p>
  <strong>News headline:</strong>
  <%= @website_detail.news_headline %>
</p>

<p>
  <strong>News coverage url:</strong>
  <%= @website_detail.news_coverage_url %>
</p>

<p>
  <strong>News desc:</strong>
  <%= @website_detail.news_desc %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @website_detail.job_title %>
</p>

<p>
  <strong>Job desc:</strong>
  <%= @website_detail.job_desc %>
</p>

<p>
  <strong>Cp heading:</strong>
  <%= @website_detail.cp_heading %>
</p>

<p>
  <strong>Cp desc:</strong>
  <%= @website_detail.cp_desc %>
</p>

<p>
  <strong>Products:</strong>
  <%= @website_detail.products %>
</p>

<p>
  <strong>Team:</strong>
  <%= @website_detail.team %>
</p>

<p>
  <strong>Cert heading:</strong>
  <%= @website_detail.cert_heading %>
</p>

<p>
  <strong>Cert details:</strong>
  <%= @website_detail.cert_details %>
</p>

<p>
  <strong>Valid from:</strong>
  <%= @website_detail.valid_from %>
</p>

<p>
  <strong>Valid till:</strong>
  <%= @website_detail.valid_till %>
</p>

<p>
  <strong>Issued on:</strong>
  <%= @website_detail.issued_on %>
</p>

<p>
  <strong>Issued by:</strong>
  <%= @website_detail.issued_by %>
</p>

<p>
  <strong>Honour award:</strong>
  <%= @website_detail.honour_award %>
</p>

<p>
  <strong>Patents:</strong>
  <%= @website_detail.patents %>
</p>

<p>
  <strong>Trademarks:</strong>
  <%= @website_detail.trademarks %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @website_detail.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @website_detail.updated_by %>
</p>

<p>
  <strong>Deleted by:</strong>
  <%= @website_detail.deleted_by %>
</p>

<p>
  <strong>User:</strong>
  <%= @website_detail.user %>
</p>

<%= link_to 'Edit', edit_website_detail_path(@website_detail) %> |
<%= link_to 'Back', website_details_path %>